global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus # 抓取自身
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: node # 抓取 node-exporter
    static_configs:
    - targets: ['service:9100'] # NOT localhost since we named the host of service in docker-compose file

